name: jokee_single_serving
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen: ^5.4.0
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

flutter_gen:
  output: lib/constants/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/image/